version: '3.3'

services:
  db:
    restart: always
    image: mysql/mysql-server:5.7.28
    container_name: mlflow_db
    expose:
      - "3306"
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
  web:
    restart: always
    build:
      context: .
      dockerfile: ./mlflow.dockerfile
    image: mlflow_server
    container_name: mlflow_server
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    volumes:
      - ${MLFLOW_VOLUME}:${MLFLOW_VOLUME}
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root /data/gblanco/mlflow/ --host 0.0.0.0        

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge

volumes:
  dbdata:
    driver: local
